version: '3.3'

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.94.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config-${NETWORK:-mocha}.yaml:/etc/otel-collector-config.yaml
    ports:
      - ${OTEL_GRPC_PORT:-4317}:${OTEL_GRPC_PORT:-4317}
      - ${OTEL_HTTP_PORT:-4318}:${OTEL_HTTP_PORT:-4318}
      - ${OTEL_PROMETHEUS_EXPORTER:-8888}:8888